### ISSUE TITLE
GPS example not working

### ISSUE THREAD

**Issue by xavierflorensa** [lewisxhe/Acsip-S7xG-Library#2]
Dear Lewis, I had  success with your ttn_abp example but no success with your gps example:
I get following result

![error gps](https://user-images.githubusercontent.com/55208134/126027465-2553fbd3-5f45-4b7a-8a9a-6071aedef92b.jpg)

![image](https://user-images.githubusercontent.com/55208134/126027421-73d62f1f-9b9b-4ec9-ab19-4af435711561.png)

**Comment by lewisxhe** [comment]
Late reply, if the GPS is not successful, it is likely that the GPS crystal oscillator has failed. This is a problem often encountered by S76G. In this case, only the hardware can be replaced
